@API_URL = http://localhost:8080


POST {{API_URL}}/api/auth/login
Content-Type: application/json

{
    "correo":"feli5@testtest.com",
    "password": "123232445"
}

###

GET {{API_URL}}/api/categorias
Content-Type: application/json
x-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MTkxOGFiYzllYWJjMGQ5NWQ1N2U3NDMiLCJpYXQiOjE2MzcwOTMwOTksImV4cCI6MTYzNzEwNzQ5OX0.VaSkCBVWd6f9NMyIoXe22RfZjYsyC9qTVY4845wvK_A

{
    "correo":"feli5@testtest.com",
    "password": "123232445"
}

###

GET {{API_URL}}/api/buscar/productos/a
Content-Type: application/json
x-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MTkxOGFiYzllYWJjMGQ5NWQ1N2U3NDMiLCJpYXQiOjE2MzcwOTMwOTksImV4cCI6MTYzNzEwNzQ5OX0.VaSkCBVWd6f9NMyIoXe22RfZjYsyC9qTVY4845wvK_A

{
    "correo":"feli5@testtest.com",
    "password": "123232445"
}